description: MNIST GAN Pytorch Const
entrypoint: gan:GANTrial

records_per_epoch: 60000 # for mnist

min_validation_period:
  batches: 500

min_checkpoint_period:
  epochs: 5

resources:
  slots_per_trial: 1
  agent_label: dt-cluster

checkpoint_storage:
  save_trial_best: 1
  save_trial_latest: 1
  save_experiment_best: 1

hyperparameters:
  global_batch_size: 32
  lr: 0.0002
  b1: 0.5
  b2: 0.999

  latent_dim: 100

searcher:
  name: single
  metric: instability
  smaller_is_better: true
  max_length:
    batches: 200000

environment:
  image:
    cpu: "deepprojects/determined-pytorch-1.7-tf-2.2-cpu"
    gpu: "deepprojects/determined-cuda-10.1-pytorch-1.7-tf-2.2-gpu"

bind_mounts:
  - host_path: /data/ldap/stachc/datasets
    container_path: /datasets
    read_only: true