description: MNIST GAN Pytorch Const
entrypoint: gan:GANTrial

min_validation_period:
  batches: 1000

resources:
  slots_per_trial: 1
  agent_label: dt-cluster

hyperparameters:
  global_batch_size: 32
  lr: 0.0002
  b1: 0.5
  b2: 0.999
  latent_dim: 100

searcher:
  name: single
  metric: stability
  smaller_is_better: false
  max_length:
    batches: 100000

environment:
  image:
    cpu: "deepprojects/determined-pytorch-1.6-tf-2.2-cpu"
    gpu: "deepprojects/determined-cuda-10.1-pytorch-1.6-tf-2.2-gpu"

bind_mounts:
  - host_path: /data/ldap/stachc/datasets
    container_path: /datasets
    read_only: true