description: MSG GAN Const
data:
  url: "https://s3-us-west-2.amazonaws.com/determined-ai-test-data/pytorch_mnist.tar.gz"
hyperparameters:
  global_batch_size: 32
  lr: 0.0002
  b1: 0.5
  b2: 0.999
  latent_dim: 100

  filter_multiplier: 4
  min_filters: 0
  max_filters: 0
  spectral_normalization: True

  latent_dimension: 256
  image_size: 256
  image_channels: 1
searcher:
  name: single
  metric: loss
  max_length:
    batches: 40000
  smaller_is_better: True
entrypoint: msg_gan:MsgGanTrail