description: MSG GAN Const
entrypoint: msg_gan:MsgGANTrail

min_validation_period:
  batches: 500

resources:
  slots_per_trial: 1
  agent_label: dt-cluster

hyperparameters:
  global_batch_size: 32
  lr: 0.0002
  b1: 0.5
  b2: 0.999

  filter_multiplier: 4
  min_filters: 0
  max_filters: 0
  spectral_normalization: true

  latent_dimension: 256
  image_size: 32
  image_channels: 1

searcher:
  name: single
  metric: 32x32_instability
  smaller_is_better: true
  max_length:
    batches: 200000

environment:
  image:
    cpu: "deepprojects/determined-pytorch-1.6-tf-2.2-cpu"
    gpu: "deepprojects/determined-cuda-10.1-pytorch-1.6-tf-2.2-gpu"

bind_mounts:
  - host_path: /data/ldap/stachc/datasets
    container_path: /datasets
    read_only: true