description: MSG GAN Const
entrypoint: msg_gan:MsgGANTrail

# records_per_epoch: 60000 # for mnist
records_per_epoch: 30000 # for celebAHQ

min_validation_period:
  batches: 500

resources:
  slots_per_trial: 1
  agent_label: dt-cluster

hyperparameters:
  global_batch_size: 32

  loss_fn: WGAN
  optimizer: Adam
  lr: 0.0003
  b1: 0.5
  b2: 0.999

  path_length_regularizer_coefficient: 0.0
  gradient_penalty_coefficient: 10.0

  filter_multiplier: 4
  min_filters: 0
  max_filters: 256
  latent_dimension: 256

  ema: true
  ema_decay: 0.999
  spectral_normalization: true
  normalize_latent: true
  image_size: 128
  image_channels: 3

searcher:
  name: single
  metric: 128x128_instability
  smaller_is_better: true
  max_length:
    epochs: 500

environment:
  image:
    cpu: "deepprojects/determined-pytorch-1.6-tf-2.2-cpu"
    gpu: "deepprojects/determined-cuda-10.1-pytorch-1.6-tf-2.2-gpu"

bind_mounts:
  - host_path: /data/ldap/stachc/datasets
    container_path: /datasets
    read_only: true