description: MSG GAN Const
entrypoint: msg_gan:MsgGANTrail

# records_per_epoch: 60000 # for mnist
records_per_epoch: 30000 # for celebAHQ
# records_per_epoch: 70000 # for ffhq

min_validation_period:
  batches: 500

min_checkpoint_period:
  epochs: 5

resources:
  slots_per_trial: 1
  agent_label: dt-cluster

checkpoint_storage:
  save_trial_best: 1
  save_trial_latest: 1
  save_experiment_best: 1

hyperparameters:
  global_batch_size: 32

  loss_fn: RaHinge
  optimizer: OAdam
  # lr: 0.0001 # Good value from OAdam paper
  lr: 0.0003 # Value from RaHinge paper as far as I remember
  b1: 0.5
  b2: 0.999

  path_length_regularizer_coefficient: 0.0
  gradient_penalty_coefficient: 10.0
  g_orthogonal_regularizer_coefficient: 0.0
  d_orthogonal_regularizer_coefficient: 0.0

  depth: 4
  min_filters: 0
  max_filters: 256
  latent_dimension: 512

  ema: true
  ema_decay: 0.999
  g_normalization: switchable
  g_spectral_normalization: false
  d_spectral_normalization: true
  instance_noise_until: 0
  clip_grad_norm: 0

  image_size: 128
  image_channels: 3

  inception_score_images: 2048
  evaluation_model: "vggface2"

searcher:
  name: single
  metric: inception_score
  smaller_is_better: false
  max_length:
    epochs: 200

environment:
  image:
    cpu: "deepprojects/determined-pytorch-1.7-tf-2.2-cpu"
    gpu: "deepprojects/determined-cuda-10.1-pytorch-1.7-tf-2.2-gpu"

bind_mounts:
  - host_path: /data/ldap/stachc/datasets
    container_path: /datasets
    read_only: true